version: '3.8'

services:
    mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - mq_config:/mosquitto/config
            - mq_data:/mosquitto/data
            - mq_log:/mosquitto/log
        networks:
            - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge
volumes:
  mq_config:
    external: true
  mq_data:
    external: true
  mq_log:
    external: true