version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - zb_data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=America/New_York
    devices:
      # Make sure this matched your adapter location
      # usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00
      # usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230804110444-if00
      # usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230804110444-if00
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230804110444-if00:/dev/ttyACM0

volumes:
  zb_data:
    external: true